[package]
name = "quantum-echoes"
version = "0.1.0"
edition = "2024"

[dependencies]
vulkano = "0.35.0"
vulkano-util = "0.35.0"
vulkano-shaders = "0.35.0"
winit = {version = "0.30.12", features = ["rwh_06"] }
egui_winit_vulkano = "0.28.0"